### ISSUE TITLE
crash when write pokemon datta

### ISSUE THREAD

**Issue by kazzaluis** [xSillusx/PQSE#4]
when i change the pokemon number in dex, it crashes

**Comment by xSillusx** [comment]
Could you give more context please? What is the exact step-by-step you do to perform this crash. I am thankful for your time!

**Comment by kazzaluis** [comment]
when i'm on dragonite, i change the dex number from 149 to 148 and the save editor crashea

**Comment by Stoned1337** [comment]
Dex Numbers are Hardcoded. I Think. 
You Can´t change this. :D

**Comment by xSillusx** [comment]
@Stoned1337 the dex numbers are dynamic. So if you want your starter Evoli to be a Mewtu, you can do that. But it shouldnt crash...will investigate soon. ^^ (Ofc you cant go above 151 cause kanto => the game will crash when you try to start the game with a pokemon thats above 151, maybe if they update johto into it, this barrier will be gone)

**Comment by xSillusx** [comment]
This issue got fixed with the latest release (https://github.com/xSillusx/PQSE/releases/tag/0.5)
I hope so....if not comment please :)
