### ISSUE TITLE
issue in the  6f7a616 0.5

### ISSUE THREAD

**Issue by kazzaluis** [xSillusx/PQSE#5]
![image](https://user-images.githubusercontent.com/1984839/41370166-7cdd1a6c-6f0c-11e8-8727-7206b9914706.png)

when you load an other save in the same windows and click on the other save lines

**Comment by xSillusx** [comment]
Wow, already found an issue. Thanks! Will fix it right away! I actually died lol

**Comment by xSillusx** [comment]
This isssue was fixed with https://github.com/xSillusx/PQSE/commit/489756492ded10560d7cd4bf9abb58ac493aaf3f
