### ISSUE TITLE
Shiny don't work 

### ISSUE THREAD

**Issue by kazzaluis** [xSillusx/PQSE#6]
6f7a616

**Comment by kazzaluis** [comment]
all other options works fine

**Comment by xSillusx** [comment]
- correct, that button was a mistake, i didnt remove it. It does not have functionality yet. Sorry to disapoint

**Comment by kazzaluis** [comment]
NP great work!!! will you put to edit stone's Abilities?

**Comment by xSillusx** [comment]
yes its written down in the future implementation

**Comment by kazzaluis** [comment]
damn!! bro i love you :D will you put to edit move set? i want a mew with bulk up xD

**Comment by xSillusx** [comment]
that aswell! I think the move editor will be set up in the next couple of days. Dont know how much time i can invest.

**Comment by kazzaluis** [comment]
change a shiny mewtwo for a mew and keep retaining its shiny status, and the mewtwo attack but when making an attack change it learned attacks that only mew learn and everything follows its normal course

**Comment by kazzaluis** [comment]
Something else is not recorded in the dex the mew shiny when I made the switch from mewtwo to mew

**Comment by kazzaluis** [comment]
when you edit the base attack amount of the Pokémon, it increases by 100 more

**Comment by xSillusx** [comment]
by exactly 100? can you confirm for every change you do? will have to look into to then more closely. Sorry 👍

**Comment by kazzaluis** [comment]
let me check

**Comment by kazzaluis** [comment]
yes , confirmed 100 more

**Comment by xSillusx** [comment]
Shinies potetnially fixed with release: https://github.com/xSillusx/PQSE/releases/tag/0.5.1
