### ISSUE TITLE
0.6

### ISSUE THREAD

**Issue by kazzaluis** [xSillusx/PQSE#8]
![image](https://user-images.githubusercontent.com/1984839/41427924-1aeec630-6fce-11e8-8410-128b0d3379d2.png)

**Comment by kazzaluis** [comment]
shiny work but when you go to pokedex, shiny is not in dex info

**Comment by realTobby** [comment]
Currently not able to fix the pokedex seen entrys. Maybe I will find a way (OR SOMEONE ELSE AND DONT MIND SHARING)
